DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

asset/urls.py
from django.conf.urls import url
from . import api
from  .import views

urlpatterns = [
    url(r'^asset.html$',views.AssetListAll.as_view(),name='asset_list'),
    url(r'^asset-add.html$',views.AssetAdd.as_view(),name='asset_add'),
    url(r'^asset-del.html$',views.AssetDel.as_view(),name='asset_del'),
    url(r'^asset-all-del.html$',views.asset_all_del,name='asset_all_del'),
    url(r'^asset-detail-(?P<pk>\d+).html$',views.AssetDetail.as_view(),name='asset_detail'),
    url(r'^asset-update-(?P<pk>[0-9]+).html$', views.AssetUpdate.as_view(), name='asset_update'),





    url(r'^asset-hardware-update.html$', views.asset_hardware_update, name='asset_hardware_update'),
    url(r'^asset-performance-(?P<nid>\d+).html$', views.asset_performance, name='asset_performance'),
    url(r'^asset-webssh.html$', views.asset_web_ssh, name='asset_web_ssh'),


    url(r'^system-user.html$', views.system_user_list, name='system_user'),
    url(r'^system-user-asset-(?P<nid>\d+).html$', views.system_user_asset, name='system_user_asset'),
    url(r'^system-user-add.html$', views.system_user_add, name='system_user_add'),
    url(r'^system-user-del.html$', views.system_user_del, name='system_user_del'),
    url(r'^system-user-detail-(?P<nid>\d+).html$', views.system_user_detail, name='system_user_detail'),
    url(r'^system-user-update-(?P<nid>\d+).html$', views.system_user_update, name='system_user_update'),
    
    url(r'^api/asset.html$',api.AssetList.as_view(),name='asset_api_list'),
    url(r'^api/asset-detail-(?P<pk>\d+).html$', api.AssetDetail.as_view(), name='asset_api_detail'),
]

autoops/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin1"),
    url(r'^$', index),
    url(r'^login.html$', login_view,name="login_view"),
    url(r'^logout.html$', logout,name="logout"),
    url(r'^index.html$', index),
    url(r'^asset/', include('asset.urls', namespace="asset", app_name='asset'), ),
    url(r'^tasks/', include('tasks.urls', namespace="tasks", app_name='tasks'), ),
    url(r'^names/', include('names.urls', namespace="names", app_name='names'), ),
    url(r'^library/', include('library.urls', namespace="library", app_name='library'), ),
    url(r'^upload/',  AssetUpload.as_view()),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


asset/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from    django.utils.decorators import method_decorator
from asset.models import asset, system_users, performance, web_history
from .form import AssetForm, SystemUserForm
import json
from django.contrib.auth.models import User, Group
from guardian.shortcuts import assign_perm, get_perms
from guardian.core import ObjectPermissionChecker
from guardian.decorators import permission_required_or_403
from tasks.views import ssh
from guardian.shortcuts import get_objects_for_user, get_objects_for_group
from guardian.models import UserObjectPermission, GroupObjectPermission
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from tasks.views import ssh

# from common.mixins import JSONResponseMixin

from  tasks.ansible_runner.runner import AdHocRunner
from django.db.models import Q


class AssetListAll(TemplateView):
    template_name = 'asset/asset.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssetListAll, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
            'asset_list': get_objects_for_user(self.request.user, 'asset.read_asset')
        }
        kwargs.update(context)
        return super(AssetListAll, self).get_context_data(**kwargs)

    def post(self, request):
        query = request.POST.get("name")
        print(query)
        a = asset.objects.filter(
            Q(network_ip=query) | Q(manage_ip=query) | Q(hostname=query) | Q(inner_ip=query) | Q(model=query) | Q(
                eth0=query) | Q(eth1=query) | Q(eth2=query) | Q(eth3=query) |
            Q(system=query) | Q(system_user__username=query) | Q(data_center__data_center_list=query) | Q(
                cabinet=query) |
            Q(position=query) | Q(sn=query)
            | Q(uplink_port=query) |
            Q(product_line__name=query))

        return render(request, 'asset/asset.html',
                      {"asset_active": "active", "asset_list_active": "active", "asset_list": a})


class AssetAdd(CreateView):
    model = asset
    form_class = AssetForm
    template_name = 'asset/asset-add.html'
    success_url = reverse_lazy('asset:asset_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('asset.add_asset'))
    def dispatch(self, *args, **kwargs):
        return super(AssetAdd, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.asset_save = asset_save = form.save()
        myproduct = asset.objects.get(network_ip=form.cleaned_data['network_ip']).product_line
        mygroup = Group.objects.get(name=myproduct)
        GroupObjectPermission.objects.assign_perm("read_asset", mygroup, obj=asset_save)
        GroupObjectPermission.objects.assign_perm("add_asset", mygroup, obj=asset_save)
        GroupObjectPermission.objects.assign_perm("change_asset", mygroup, obj=asset_save)
        GroupObjectPermission.objects.assign_perm("delete_asset", mygroup, obj=asset_save)
        return super(AssetAdd, self).form_valid(form)

    def get_success_url(self):
        return super(AssetAdd, self).get_success_url()

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }
        kwargs.update(context)
        return super(AssetAdd, self).get_context_data(**kwargs)


class AssetUpdate(UpdateView):
    model = asset
    form_class = AssetForm
    template_name = 'asset/asset-update.html'
    success_url = reverse_lazy('asset:asset_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('asset.add_asset', (asset, 'id', 'pk')))
    def dispatch(self, *args, **kwargs):
        return super(AssetUpdate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }
        kwargs.update(context)
        return super(AssetUpdate, self).get_context_data(**kwargs)

    def form_invalid(self, form):
        print(form.errors)
        return super(AssetUpdate, self).form_invalid(form)

    def form_valid(self, form):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        oldmyproduct = asset.objects.get(id=pk).product_line
        oldmygroup = Group.objects.get(name=oldmyproduct)
        self.object = form.save()
        myproduct = asset.objects.get(id=pk).product_line
        mygroup = Group.objects.get(name=myproduct)

        if oldmygroup != mygroup:
            GroupObjectPermission.objects.filter(object_pk=pk).delete()
            GroupObjectPermission.objects.assign_perm("read_asset", mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("add_asset", mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("change_asset", mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("delete_asset", mygroup, obj=self.object)
        return super(AssetUpdate, self).form_valid(form)

    def get_success_url(self):
        return super(AssetUpdate, self).get_success_url()


class AssetDetail(DetailView):
    model = asset
    template_name = 'asset/asset-detail.html'

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('asset.change_asset', (asset, 'id', 'pk')))
    def dispatch(self, *args, **kwargs):
        return super(AssetDetail, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        detail = asset.objects.get(id=pk)
        print(detail.file)
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
            "assets": detail,
            "nid": pk,
        }
        kwargs.update(context)
        return super(AssetDetail, self).get_context_data(**kwargs)


class AssetDel(View):
    model = asset

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssetDel, self).dispatch(*args, **kwargs)

    def post(self, request):
        ret = {'status': True, 'error': None, }
        try:
            id = request.POST.get('nid', None)
            user = User.objects.get(username=request.user)
            checker = ObjectPermissionChecker(user)
            assets = asset.objects.get(id=id)
            if checker.has_perm('delete_asset', assets, ) == True:
                assets.delete()
                GroupObjectPermission.objects.filter(object_pk=id).delete()
        except Exception as e:
            ret = {
                "static": False,
                "error": '删除请求错误,{}'.format(e)
            }
        return   HttpResponse(json.dumps(ret))


@login_required(login_url="/login.html")
def asset_all_del(request):
    ret = {'status': True, 'error': None, }
    if request.method == "POST":
        try:
            ids = request.POST.getlist('id', None)
            ids1 = []
            for i in ids:
                user = User.objects.get(username=request.user)
                checker = ObjectPermissionChecker(user)
                assets = asset.objects.get(id=i)
                if checker.has_perm('delete_asset', assets, ) == True:
                    ids1.append(i)

            idstring = ','.join(ids1)
            asset.objects.extra(where=['id IN (' + idstring + ')']).delete()
            GroupObjectPermission.objects.extra(where=['object_pk IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,{}'.format(e)
        return HttpResponse(json.dumps(ret))


@login_required(login_url="/login.html")
def asset_hardware_update(request):
    ret = {'status': True, 'error': None, 'data': None}

    if request.method == 'POST':
        try:
            id = request.POST.get('nid', None)
            obj = asset.objects.get(id=id)
            ip = obj.network_ip
            port = obj.port
            username = obj.system_user.username
            password = obj.system_user.password
            assets = [
                {
                    "hostname": 'host',
                    "ip": ip,
                    "port": port,
                    "username": username,
                    "password": password,
                },
            ]


            task_tuple = (('setup', ''),)
            runner = AdHocRunner(assets)
            result = runner.run(task_tuple=task_tuple, pattern='all', task_name='Ansible Ad-hoc')

            data = result['contacted']['host'][0]['ansible_facts']

            hostname = data['ansible_nodename']
            system = data['ansible_distribution'] + " " + data['ansible_distribution_version']


            try:
                a2 = "parted -l  | grep   \"Disk \/dev\/[a-z]d\"  | awk -F\"[ ]\"  '{print $3}' | awk  -F\"GB\"  '{print $1}'"
                s = ssh(ip=ip, port=port, username=username, password=password, cmd=a2)
                disk1 = s['data']
                disk2 = disk1.rstrip().split("\n")
                disk = "+".join(map(str, disk2)) + "   共计:{} GB".format(round(sum(map(float, disk2))))
            except Exception  as  e:

                disk =  " 共计{}".format(str(sum([int(data["ansible_devices"][i]["sectors"]) * \
                             int(data["ansible_devices"][i]["sectorsize"]) / 1024 / 1024 / 1024 \

templates/asset/system-user-asset.html
{% extends "base.html" %}
{% block  title %}关联资产{% endblock %}
{% block header-css %}

{% load	bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>关联资产</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="/asset/system-user.html">用户管理</a>
                </li>
                <li class="active">
                    <strong>关联资产</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">
                            <li >
                                <a   href="{% url "asset:system_user_detail"  nid  %}" class="text-center"><i class="fa fa-laptop"></i>用户详情</a>
                            </li>
                              <li class="active">

                                <a class="text-center"    ><i class="fa fa-laptop"></i>关联资产</a>
                            </li>
                            <li class="pull-right">
                                <a class="btn btn-outline btn-default" href="{% url "asset:system_user_update"  nid %}"><i
                                        class="fa fa-edit"></i>编辑</a>
                            </li>
                            <li class="pull-right">
                                <a class="btn btn-outline btn-danger" data-toggle="modal" data-target="#myModal1">
                                    <i class="fa fa-edit"></i>删除
                                </a>
                            </li>

                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="col-sm-7" style="padding-left: 0">
                     <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>关联资产</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                <tr>
                                    <th>主机名</th>
                                    <th>外网IP</th>
                                    <th>管理IP</th>
                                    <th>端口</th>
                                    <th>产品线</th>
                                    <th>动作</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for   row   in   asset_list %}
                                    <tr class="gradeA" id="{{ row.id }}">
                                        <td class="center"><a  href="{% url  "asset:asset_detail"   row.id %}">{{ row.hostname }}</a></td>
                                        <td class="center">{{ row.network_ip }}</td>
                                        <td class="center">{{ row.manage_ip }}</td>
                                        <td class="center">{{ row.port }}</td>
                                        <td class="center">{{ row.product_line }}</td>
                                        <td><a   class="btn btn-primary btn-xs"
                                               href="{% url  "asset:asset_update"   row.id %}">编辑</a>
                                            <button  class="btn btn-danger btn-xs  asset_del_id"
                                                    data-toggle="modal"
                                                    data-target="#myModal1">删除
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>主机名</th>
                                    <th>外网IP</th>
                                    <th>管理IP</th>
                                    <th>端口</th>
                                    <th>产品线</th>
                                    <th>动作</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>
                </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal inmodal" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">删除</h4>
                    <span id="error" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="asset_del_form">
                    <div class="modal-body">

                        <div class="form-group"><input type="text" name="nid" style="display:none" value="{{ nid }}"/>
                        </div>
                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm system_user_del">删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    {% block footer-js %}
        <script>
            $(function () {
                $('.system_user_del').click(function () {
                    $.ajax({
                        url: "/asset/system-user-del.html",
                        type: 'POST',
                        data: $('#asset_del_form').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.href = "{% url "asset:system_user" %}"
                            } else {
                                $('#error').text(obj.error);
                            }
                        }
                    })
                });

            });
        </script>


    {% endblock %}


{% endblock %}

templates/asset/system-user-detail.html
{% extends "base.html" %}
{% block  title %}系统用户详情{% endblock %}
{% block header-css %}

{% load	bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>系统用户详情</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="/asset/system-user.html">用户管理</a>
                </li>
                <li class="active">
                    <strong>系统用户详情</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a class="text-center"><i class="fa fa-laptop"></i>用户详情</a>
                            </li>
                              <li>

                                <a class="text-center"  href="{% url "asset:system_user_asset"  nid  %}"  ><i class="fa fa-laptop"></i>关联资产</a>
                            </li>
                            <li class="pull-right">
                                <a class="btn btn-outline btn-default" href="{% url "asset:system_user_update"  nid %}"><i
                                        class="fa fa-edit"></i>编辑</a>
                            </li>
                            <li class="pull-right">
                                <a class="btn btn-outline btn-danger" data-toggle="modal" data-target="#myModal1">
                                    <i class="fa fa-edit"></i>删除
                                </a>
                            </li>

                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="col-sm-7" style="padding-left: 0">
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <span class="label"><b>{{ system_users.name }}</b></span>
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            <i class="fa fa-wrench"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown-user">
                                        </ul>
                                        <a class="close-link">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="ibox-content">

                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <td style=" border-top: none !important;" width="20%">名称</td>
                                            <td style=" border-top: none !important;"><b>{{ system_users.name}}</b>
                                            </td>
                                        </tr>
                                         <tr>
                                            <td width="20%">登陆用户</td>
                                            <td><b>{{ system_users.username }}</b></td>
                                        </tr>
                                         <tr>
                                            <td width="20%">产品线</td>
                                            <td><b>{{ system_users.product_line }}</b></td>
                                        </tr>
                                        <tr>
                                            <td width="20%">备注</td>
                                            <td><b>{{ system_users.ps }}</b></td>
                                        </tr>
                                        <tr>
                                            <td width="20%">创建时间</td>
                                            <td><b>{{ system_users.ctime }}</b></td>
                                        </tr>
                                        <tr>
                                            <td width="20%">更新时间</td>
                                            <td><b>{{ system_users.utime }}</b></td>
                                        </tr>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal inmodal" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">删除</h4>
                    <span id="error" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="asset_del_form">
                    <div class="modal-body">

                        <div class="form-group"><input type="text" name="nid" style="display:none" value="{{ nid }}"/>
                        </div>
                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm system_user_del">删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    {% block footer-js %}
        <script>
            $(function () {
                $('.system_user_del').click(function () {
                    $.ajax({
                        url: "/asset/system-user-del.html",
                        type: 'POST',
                        data: $('#asset_del_form').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.href = "{% url "asset:system_user" %}"
                            } else {
                                $('#error').text(obj.error);
                            }
                        }
                    })
                });

            });
        </script>


    {% endblock %}


{% endblock %}