DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

asset/urls.py
from django.conf.urls import url
from . import api
from  .import views

urlpatterns = [
    url(r'^asset.html$',views.AssetListAll.as_view(),name='asset_list'),
    url(r'^asset-add.html$',views.AssetAdd.as_view(),name='asset_add'),
    url(r'^asset-del.html$',views.AssetDel.as_view(),name='asset_del'),
    url(r'^asset-all-del.html$',views.asset_all_del,name='asset_all_del'),
    url(r'^asset-detail-(?P<pk>\d+).html$',views.AssetDetail.as_view(),name='asset_detail'),
    url(r'^asset-update-(?P<pk>[0-9]+).html$', views.AssetUpdate.as_view(), name='asset_update'),





    url(r'^asset-hardware-update.html$', views.asset_hardware_update, name='asset_hardware_update'),
    url(r'^asset-performance-(?P<nid>\d+).html$', views.asset_performance, name='asset_performance'),
    url(r'^asset-webssh.html$', views.asset_web_ssh, name='asset_web_ssh'),


    url(r'^system-user.html$', views.system_user_list, name='system_user'),
    url(r'^system-user-asset-(?P<nid>\d+).html$', views.system_user_asset, name='system_user_asset'),
    url(r'^system-user-add.html$', views.system_user_add, name='system_user_add'),
    url(r'^system-user-del.html$', views.system_user_del, name='system_user_del'),
    url(r'^system-user-detail-(?P<nid>\d+).html$', views.system_user_detail, name='system_user_detail'),
    url(r'^system-user-update-(?P<nid>\d+).html$', views.system_user_update, name='system_user_update'),
    
    url(r'^api/asset.html$',api.AssetList.as_view(),name='asset_api_list'),
    url(r'^api/asset-detail-(?P<pk>\d+).html$', api.AssetDetail.as_view(), name='asset_api_detail'),
]

autoops/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin1"),
    url(r'^$', index),
    url(r'^login.html$', login_view,name="login_view"),
    url(r'^logout.html$', logout,name="logout"),
    url(r'^index.html$', index),
    url(r'^asset/', include('asset.urls', namespace="asset", app_name='asset'), ),
    url(r'^tasks/', include('tasks.urls', namespace="tasks", app_name='tasks'), ),
    url(r'^names/', include('names.urls', namespace="names", app_name='names'), ),
    url(r'^library/', include('library.urls', namespace="library", app_name='library'), ),
    url(r'^upload/',  AssetUpload.as_view()),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


library/urls.py
from django.conf.urls import url

from  .import views

urlpatterns = [
    url(r'^library.html$', views.LibraryListAll.as_view(), name='library_list'),
    url(r'^library-add.html$', views.LibraryAdd.as_view(), name='library_add'),
    url(r'^library-update-(?P<pk>[0-9]+).html$', views.LibraryUpdate.as_view(), name='library_update'),
    url(r'^library-del.html$',views.LibraryDel.as_view(),name='library_del'),
    url(r'^library-detail-(?P<pk>\d+).html$', views.LibraryDetail.as_view(), name='library_detail'),
]

names/urls.py
from django.conf.urls import url

from  .import views

urlpatterns = [
    url(r'^login-history.html$',views.login_history,name="login_history"),
    url(r'^password.html$', views.password_update, name="password_update"),
    url(r'^web-history.html$', views.web_historys, name='web_history'),
    url(r'^cmd-history.html$', views.cmd_historys, name='cmd_history'),
]

tasks/urls.py
from django.conf.urls import url

from  .import views

urlpatterns = [
    url(r'^cmd.html$', views.cmd, name='cmd'),

    url(r'^tools.html$', views.tools, name='tools'),
    url(r'^tools-add.html$', views.tools_add, name='tools_add'),
    url(r'^tools-del.html$', views.tools_delete, name='tools_delete'),
    url(r'^tools-bulk-del.html$', views.tools_bulk_delte, name='tools_bulk_delte'),
    url(r'^tools-update-(?P<nid>\d+).html$', views.tools_update, name='tools_update'),
    url(r'^tools-script-(?P<nid>\d+).html$', views.tools_script_get, name='tools_script_get'),
    url(r'^tools-script.html$', views.tools_script_post, name='tools_script_post'),
]

templates/_css.html
{% load  static %}

<link href=" {% static  "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static  "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

<link href="{% static  "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css"  %} " rel="stylesheet">

<link href="{% static "css/datatables.min.css"%} "   rel="stylesheet">

<link href="{% static "css/plugins/select2/select2.min.css"%} "   rel="stylesheet">

templates/_footer.html
  <div class="footer">
            <div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2014-2017
            </div>
        </div>

templates/_js.html
{% load  static %}

<script src="{% static  "js/jquery-3.1.1.min.js"%}"></script>
<script src="{% static  "js/bootstrap.min.js"%}"></script>
<script src="{% static  "js/plugins/metisMenu/jquery.metisMenu.js"%}"></script>
<script src="{% static  "js/plugins/slimscroll/jquery.slimscroll.min.js"%}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  "js/inspinia.js"%} "></script>
<script src="{% static  "js/plugins/pace/pace.min.js"%}"></script>


<script src="{% static  "js/datatables.min.js" %}"></script>


<script src="{% static  "js/plugins/select2/select2.full.min.js" %}"></script>



<script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>




<!-- Page-Level Scripts -->
<script>
   $(document).ready(function () {
        $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            "order": [[1, 'desc']],
            columnDefs: [{
                'targets': [0],    //都默认不排序
                'orderable': false
            }],


            dom: '<"html5buttons"B>lTfgitp,',

            buttons: [],
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "全部"]]
        });


    });


       $("#CheckedAll").click(function () {
        if ($(this).is(":checked")) {
            $("[name=id]:checkbox").prop("checked", true);
        } else {
            $("[name=id]:checkbox").prop("checked", false);
        }
    });





    </script>

templates/_nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{ user }}</strong>

                             </span> <span class="text-muted text-xs block">
                                {% ifequal  user.is_superuser  1 %}
                                管理员 {% else %} 普通用户 {% endifequal %}
                                <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                          <li><a href="{% url  "names:password_update" %}">修改密码</a></li>
                        <li><a href="/logout.html">登出</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Ops
                </div>
            </li>
            <li>
                <a href="/index.html"><i class="fa fa-th-list"></i> <span class="nav-label">首页</span>
                   </a>

            </li>
            <li class="{{ asset_active }}">
                <a href="#"><i class="fa fa-drivers-license"></i> <span class="nav-label">资产管理</span>
                    <span  class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li  class="{{ asset_list_active }}"><a href="{% url    'asset:asset_list' %}">资产信息</a></li>

                    <li  class="{{ system_user_list_active }}"><a href="{% url    'asset:system_user' %}">系统用户</a></li>
                </ul>
            </li>
             <li class="{{ tasks_active }}">
                <a href="#"><i class="fa fa-address-book-o"></i> <span class="nav-label">执行任务</span>
                    <span  class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li  class="{{ cmd_active }}"><a href="{% url    'tasks:cmd' %}">命令行</a></li>
                     <li  class="{{ tools_active }}"><a href="{% url    'tasks:tools' %}">工具</a></li>

                </ul>
            </li>

            <li class="{{ library_active }}">
                <a href="#"><i class="fa fa-snapchat-ghost"></i> <span class="nav-label">技术文档</span>
                    <span  class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                     <li  class="{{ library_list_active }}"><a href="{% url    'library:library_list' %}">文档列表</a></li>
                </ul>
            </li>



              <li class="{{ autoops_active }}">
                <a href="#"><i class="fa fa-snapchat-ghost"></i> <span class="nav-label">平台管理</span>
                    <span  class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li ><a href="/admin">后台</a></li>
                    <li  class="{{ login_log_active }}"><a href="{% url    'names:login_history' %}">历史记录</a></li>
                </ul>
            </li>

        </ul>

    </div>
</nav>

templates/_navbar-static-top.html
<div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
{#                    <form role="search" class="navbar-form-custom" method="post" action="#">#}
{#                        <div class="form-group">#}
{#                            <input type="text" placeholder="请输入搜索内容" class="form-control" name="top-search" id="top-search">#}
{#                        </div>#}
{#                    </form>#}
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    欢迎 {{ user  }} 使用 AutoOps  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <li>
                        <a href="/logout.html">
                            <i class="fa fa-sign-out"></i> 注销
                        </a>
                    </li>
                </ul>

            </nav>
        </div>

templates/base.html
{% load  mytags %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block  title %}{% endblock %}</title>

    {% include  "_css.html" %}
    {% block header-css %}
    {% endblock %}

</head>

<body>

<div id="wrapper">

    {% include "_nav.html" %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "_navbar-static-top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "_footer.html" %}

    </div>
</div>


{% include  "_js.html" %}
{% block footer-js %}
{% endblock %}





</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block  title %}AutOps | 首页{% endblock %}

{% block header-css %}
{% endblock %}

{{ user }}



{% block page-content %}




{% endblock %}

{% block footer-js %}
{% endblock %}