DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

asset/urls.py
from django.conf.urls import url
from . import api
from  .import views

urlpatterns = [
    url(r'^asset.html$',views.AssetListAll.as_view(),name='asset_list'),
    url(r'^asset-add.html$',views.AssetAdd.as_view(),name='asset_add'),
    url(r'^asset-del.html$',views.AssetDel.as_view(),name='asset_del'),
    url(r'^asset-all-del.html$',views.asset_all_del,name='asset_all_del'),
    url(r'^asset-detail-(?P<pk>\d+).html$',views.AssetDetail.as_view(),name='asset_detail'),
    url(r'^asset-update-(?P<pk>[0-9]+).html$', views.AssetUpdate.as_view(), name='asset_update'),





    url(r'^asset-hardware-update.html$', views.asset_hardware_update, name='asset_hardware_update'),
    url(r'^asset-performance-(?P<nid>\d+).html$', views.asset_performance, name='asset_performance'),
    url(r'^asset-webssh.html$', views.asset_web_ssh, name='asset_web_ssh'),


    url(r'^system-user.html$', views.system_user_list, name='system_user'),
    url(r'^system-user-asset-(?P<nid>\d+).html$', views.system_user_asset, name='system_user_asset'),
    url(r'^system-user-add.html$', views.system_user_add, name='system_user_add'),
    url(r'^system-user-del.html$', views.system_user_del, name='system_user_del'),
    url(r'^system-user-detail-(?P<nid>\d+).html$', views.system_user_detail, name='system_user_detail'),
    url(r'^system-user-update-(?P<nid>\d+).html$', views.system_user_update, name='system_user_update'),
    
    url(r'^api/asset.html$',api.AssetList.as_view(),name='asset_api_list'),
    url(r'^api/asset-detail-(?P<pk>\d+).html$', api.AssetDetail.as_view(), name='asset_api_detail'),
]

autoops/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin1"),
    url(r'^$', index),
    url(r'^login.html$', login_view,name="login_view"),
    url(r'^logout.html$', logout,name="logout"),
    url(r'^index.html$', index),
    url(r'^asset/', include('asset.urls', namespace="asset", app_name='asset'), ),
    url(r'^tasks/', include('tasks.urls', namespace="tasks", app_name='tasks'), ),
    url(r'^names/', include('names.urls', namespace="names", app_name='names'), ),
    url(r'^library/', include('library.urls', namespace="library", app_name='library'), ),
    url(r'^upload/',  AssetUpload.as_view()),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


library/urls.py
from django.conf.urls import url

from  .import views

urlpatterns = [
    url(r'^library.html$', views.LibraryListAll.as_view(), name='library_list'),
    url(r'^library-add.html$', views.LibraryAdd.as_view(), name='library_add'),
    url(r'^library-update-(?P<pk>[0-9]+).html$', views.LibraryUpdate.as_view(), name='library_update'),
    url(r'^library-del.html$',views.LibraryDel.as_view(),name='library_del'),
    url(r'^library-detail-(?P<pk>\d+).html$', views.LibraryDetail.as_view(), name='library_detail'),
]

library/models.py
from django.db import models
import random
from DjangoUeditor.models import UEditorField


class librarys(models.Model):
    title = models.CharField(max_length=128, verbose_name='标题', null=True,unique=True)
    content = UEditorField('内容', height=300, width=1000,max_length=1024000000000,
                           default=u'', blank=True, imagePath="library/images/",
                           toolbars='besttome', filePath='library/files/')
    
    classify = models.CharField(max_length=128, verbose_name='分类', null=True,blank=True)
    ctime= models.DateTimeField(auto_now_add=True,null=True,verbose_name='创建时间',blank=True)
    utime = models.DateTimeField(auto_now=True, null=True,verbose_name='更新时间',blank=True)



    class  Meta:
        db_table ="librarys"
        verbose_name="技术文库"
        verbose_name_plural = '技术文库'
        permissions = {
            ('read_librarys',u"只读技术文库"),
        }

library/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from    django.utils.decorators import method_decorator
from  library.models import  librarys
from .form import  LibrarysForm
import json
from django.contrib.auth.models import User, Group
from guardian.shortcuts import assign_perm, get_perms
from guardian.core import ObjectPermissionChecker
from guardian.decorators import permission_required_or_403
from tasks.views import ssh
from guardian.shortcuts import get_objects_for_user, get_objects_for_group
from guardian.models import UserObjectPermission, GroupObjectPermission
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy



class LibraryListAll(TemplateView):
    template_name = 'library/library.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LibraryListAll, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        obj = librarys.objects.all()
        context = {
            "library_active": "active",
            "library_list_active": "active",
            'library_list': obj,
        }
        kwargs.update(context)
        return super(LibraryListAll, self).get_context_data(**kwargs)





class LibraryAdd(CreateView,View):
    model = librarys
    form_class = LibrarysForm
    template_name = 'library/library-add.html'
    success_url = reverse_lazy('library:library_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LibraryAdd, self).dispatch(*args, **kwargs)

    def form_valid(self,form,):
        self.lib_save = lib_save = form.save()

        return super(LibraryAdd, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = {
            "library_active": "active",
            "library_list_active": "active",
            
        }
        kwargs.update(context)
        return super(LibraryAdd, self).get_context_data(**kwargs)
    
    
class LibraryUpdate(UpdateView):
    model = librarys
    form_class = LibrarysForm
    template_name = 'library/library-update.html'
    success_url = reverse_lazy('library:library_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LibraryUpdate, self).dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        self.lib_save  = form.save()
        return super(LibraryUpdate, self).form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super(LibraryUpdate, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        context = {
            "library_active": "active",
            "library_list_active": "active",
        }
        kwargs.update(context)
        return super(LibraryUpdate, self).get_context_data(**kwargs)

    def get_success_url(self):
        return super(LibraryUpdate, self).get_success_url()

class LibraryDetail(DetailView):
    model = librarys
    template_name = 'library/library-detail.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LibraryDetail, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        detail = librarys.objects.get(id=pk)
        context = {
            "library_active": "active",
            "library_list_active": "active",
            "librarys": detail,
            "nid": pk,
        }
        kwargs.update(context)
        return super(LibraryDetail, self).get_context_data(**kwargs)












class LibraryDel(View):
    model = librarys
    form_class = LibrarysForm


    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LibraryDel, self).dispatch(*args, **kwargs)

    def post(self, request):
        ret = {'status': True, 'error': None, }
        try:
            id = request.POST.get('nid', None)
            lib = librarys.objects.get(id=id)
            lib.delete()
            print(ret)
        except Exception as e:
            ret = {
                "static": False,
                "error": '删除请求错误,{}'.format(e)
            }
        return HttpResponse(json.dumps(ret))

templates/library/library-add.html
{% extends "base.html" %}
{% block  title %}文档添加{% endblock %}
{% block header-css %}



{% load	bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>文档添加</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="library.html">文档列表</a>
                </li>
                <li class="active">
                    <strong>文档添加</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>文档添加</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" action="{% url "library:library_add" %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">

                            {{ form.media  }}
                             {% bootstrap_field form.title layout="horizontal" %}
                            {% bootstrap_field form.content layout="horizontal" %}
                            {% bootstrap_field form.classify layout="horizontal" %}





                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                <button class="btn btn-primary" type="submit">保存</button>
                                <button class="btn btn-white" type="reset">重置</button>
                            </div>
                        </div>

                    </form>


                </div>


            </div>
        </div>

    </div>


    {% block footer-js %}





        <script>
            $(document).ready(function () {
                $('.select2').select2();
                {#            $("#id_tags").select2({#}
                {#                tags: true,#}
                {#                maximumSelectionLength: 8  //最多能够选择的个数#}
                {#                //closeOnSelect: false#}
                {#            });#}
            })
        </script>


    {% endblock %}



{% endblock %}

templates/library/library-detail.html
{% extends "base.html" %}
{% block  title %}文档{% endblock %}

{% block header-css %}
{% endblock %}


{% block page-content %}
<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>文档</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="library.html">文档列表</a>
                </li>
                <li class="active">
                    <strong>文档</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

   <div class="wrapper wrapper-content  animated fadeInRight article">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1">
                    <div class="ibox">
                        <div class="ibox-content">
                            <div class="pull-right">
                                <button class="btn btn-white btn-xs" type="button">{{ librarys.classify }}</button>

                            </div>
                            <div class="text-center article-title">
                                    {{ librarys.ctime }}
                                <h1>
                                    {{ librarys.title }}
                                </h1>
                            </div>
                            {% autoescape off %}
                                    {{ librarys.content }}
                            {% endautoescape %}
                            <hr>





                        </div>
                    </div>
                </div>
            </div>


        </div>







{% endblock %}

{% block footer-js %}
{% endblock %}

templates/library/library-update.html
{% extends "base.html" %}
{% block  title %}文档更新{% endblock %}
{% block header-css %}



{% load	bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>文档添加</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="library.html">文档列表</a>
                </li>
                <li class="active">
                    <strong>文档添加</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>文档更新</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">

                            {{ form.media  }}
                             {% bootstrap_field form.title layout="horizontal" %}
                            {% bootstrap_field form.content layout="horizontal" %}
                            {% bootstrap_field form.classify layout="horizontal" %}
                         




                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                <button class="btn btn-primary" type="submit">保存</button>
                                <button class="btn btn-white" type="reset">重置</button>
                            </div>
                        </div>

                    </form>


                </div>


            </div>
        </div>

    </div>


    {% block footer-js %}



    {% endblock %}



{% endblock %}

templates/library/library.html
{% extends "base.html" %}


{% block  title %}技术文档{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>技术文档</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>资产管理</a>
                </li>
                <li class="active">
                    <strong>技术文档</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>技术文档</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                          <div class="table-responsive">

                            <a href="{% url  "library:library_add" %}"    class="btn btn-primary  ">
                                添加</a>






                            <form id="del_form_asset_all" class="form-horizontal  ">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
{#                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>#}
                                        <th>标题</th>
                                        <th>分类</th>
                                        <th>更新时间</th>
                                        <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   library_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
{#                                            <td><input type="checkbox" value="{{ row.id }}"  name="id"></td>#}
                                            <td class="center"><a
                                                    href="{% url  "library:library_detail"   pk=row.id %}">{{ row.title }}</a>
                                            </td>
                                            <td class="center">{{ row.classify }}</td>
                                            <td class="center">{{  row.ctime }}</td>

                                            <td><a class="btn btn-primary  btn-xs "
                                                   href="{% url  "library:library_update"  pk=row.id %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  library_del_id"     data-toggle="modal"
                                                        data-target="#myModal1">删除
                                                </a>

                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal inmodal" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">删除</h4>
                    <span id="error" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="library_del_form">
                    <div class="modal-body">

                        <div class="form-group"><input type="text" name="nid" style="display:none"/></div>
                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm asset_del">删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>





    {% block footer-js %}


        <script>
            $(function () {

                $('.library_del_id').click(function () {
                    var id = $(this).parent().parent().attr('id');
                    $('#library_del_form').find('input[name="nid"]').val(id);


                });
                $('.asset_del').click(function () {
                    $.ajax({
                        url: "/library/library-del.html",
                        type: 'POST',
                        data: $('#library_del_form').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.reload()
                            } else {
                                $('#error').text(obj.error);
                            }
                        }
                    })
                });



            });





        </script>


    {% endblock %}

{% endblock %}