DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

asset/urls.py
from django.conf.urls import url
from . import api
from  .import views

urlpatterns = [
    url(r'^asset.html$',views.AssetListAll.as_view(),name='asset_list'),
    url(r'^asset-add.html$',views.AssetAdd.as_view(),name='asset_add'),
    url(r'^asset-del.html$',views.AssetDel.as_view(),name='asset_del'),
    url(r'^asset-all-del.html$',views.asset_all_del,name='asset_all_del'),
    url(r'^asset-detail-(?P<pk>\d+).html$',views.AssetDetail.as_view(),name='asset_detail'),
    url(r'^asset-update-(?P<pk>[0-9]+).html$', views.AssetUpdate.as_view(), name='asset_update'),





    url(r'^asset-hardware-update.html$', views.asset_hardware_update, name='asset_hardware_update'),
    url(r'^asset-performance-(?P<nid>\d+).html$', views.asset_performance, name='asset_performance'),
    url(r'^asset-webssh.html$', views.asset_web_ssh, name='asset_web_ssh'),


    url(r'^system-user.html$', views.system_user_list, name='system_user'),
    url(r'^system-user-asset-(?P<nid>\d+).html$', views.system_user_asset, name='system_user_asset'),
    url(r'^system-user-add.html$', views.system_user_add, name='system_user_add'),
    url(r'^system-user-del.html$', views.system_user_del, name='system_user_del'),
    url(r'^system-user-detail-(?P<nid>\d+).html$', views.system_user_detail, name='system_user_detail'),
    url(r'^system-user-update-(?P<nid>\d+).html$', views.system_user_update, name='system_user_update'),
    
    url(r'^api/asset.html$',api.AssetList.as_view(),name='asset_api_list'),
    url(r'^api/asset-detail-(?P<pk>\d+).html$', api.AssetDetail.as_view(), name='asset_api_detail'),
]

autoops/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin1"),
    url(r'^$', index),
    url(r'^login.html$', login_view,name="login_view"),
    url(r'^logout.html$', logout,name="logout"),
    url(r'^index.html$', index),
    url(r'^asset/', include('asset.urls', namespace="asset", app_name='asset'), ),
    url(r'^tasks/', include('tasks.urls', namespace="tasks", app_name='tasks'), ),
    url(r'^names/', include('names.urls', namespace="names", app_name='names'), ),
    url(r'^library/', include('library.urls', namespace="library", app_name='library'), ),
    url(r'^upload/',  AssetUpload.as_view()),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


tasks/urls.py
from django.conf.urls import url

from  .import views

urlpatterns = [
    url(r'^cmd.html$', views.cmd, name='cmd'),

    url(r'^tools.html$', views.tools, name='tools'),
    url(r'^tools-add.html$', views.tools_add, name='tools_add'),
    url(r'^tools-del.html$', views.tools_delete, name='tools_delete'),
    url(r'^tools-bulk-del.html$', views.tools_bulk_delte, name='tools_bulk_delte'),
    url(r'^tools-update-(?P<nid>\d+).html$', views.tools_update, name='tools_update'),
    url(r'^tools-script-(?P<nid>\d+).html$', views.tools_script_get, name='tools_script_get'),
    url(r'^tools-script.html$', views.tools_script_post, name='tools_script_post'),
]

tasks/models.py
from django.db import models

class history(models.Model):
    root = models.CharField(max_length=32, verbose_name='用户', null=True)
    ip = models.GenericIPAddressField(verbose_name='IP',null=True)
    port = models.CharField(max_length=32,verbose_name='端口',null=True)
    cmd = models.CharField(max_length=128,verbose_name='命令',null=True)
    user = models.CharField(max_length=32,verbose_name='操作者',null=True)
    ctime = models.DateTimeField(auto_now_add=True, verbose_name='时间')

    class  Meta:
        db_table ="history"
        verbose_name="历史命令"
        verbose_name_plural = '历史命令'


    def __str__(self):
        return self.ip





class toolsscript(models.Model):
    TOOL_RUN_TYPE = (
        (0, 'shell'),
        (1, 'python'),
        (2, 'yml'),
    )

    name = models.CharField(max_length=255, verbose_name='工具名称',unique=True)
    tool_script = models.TextField(verbose_name='脚本',null=True, blank=True)
    tool_run_type = models.IntegerField(choices=TOOL_RUN_TYPE, verbose_name='脚本类型', default=0)
    comment = models.TextField(verbose_name='工具说明', null=True, blank=True)
    ctime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    utime = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "toolsscript"
        verbose_name = "工具"
        verbose_name_plural = verbose_name

tasks/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from  django.contrib.auth.decorators import login_required
from asset.models import asset
from .models import history, toolsscript
import paramiko, json, os
from .form import ToolForm
from guardian.shortcuts import get_objects_for_user, get_objects_for_group
from django.contrib.auth.models import User
from guardian.core import ObjectPermissionChecker

from   tasks.ansible_runner.runner      import AdHocRunner,PlayBookRunner
from   tasks.ansible_runner.callback    import CommandResultCallback


def ssh(ip, port, username, password, cmd):
    try:
        ssh = paramiko.SSHClient()  # 创建ssh对象
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(hostname=ip, port=int(port), username=username, password=password, )
        stdin, stdout, stderr = ssh.exec_command(cmd, timeout=10)
        result = stdout.read()
        result1 = result.decode()
        error = stderr.read().decode('utf-8')

        if not error:
            ret = {"ip": ip, "data": result1}
            ssh.close()
            return ret
    except Exception as e:
        error = "账号或密码错误,{}".format(e)
        ret = {"ip": ip, "data": error}
        return ret


@login_required(login_url="/login.html")
def cmd(request):  ##命令行

    if request.method == "GET":
        obj = get_objects_for_user(request.user, 'asset.change_asset')
        return render(request, 'tasks/cmd.html', {'asset_list': obj, "tasks_active": "active", "cmd_active": "active"})

    if request.method == 'POST':
        ids = request.POST.getlist('id')
        cmd = request.POST.get('cmd', None)

        user = User.objects.get(username=request.user)
        checker = ObjectPermissionChecker(user)
        ids1 = []
        for i in ids:
            assets = asset.objects.get(id=i)
            if checker.has_perm('delete_asset', assets, ) == True:
                ids1.append(i)

        user = request.user
        idstring = ','.join(ids1)
        if not ids:
            error_1 = "请选择主机"
            ret = {"error": error_1, "status": False}
            return HttpResponse(json.dumps(ret))
        elif not cmd:
            error_2 = "请输入命令"
            ret = {"error": error_2, "status": False}
            return HttpResponse(json.dumps(ret))

        obj = asset.objects.extra(where=['id IN (' + idstring + ')'])

        ret = {}

        ret['data'] = []
        for i in obj:
            try:
                s = ssh(ip=i.network_ip, port=i.port, username=i.system_user.username, password=i.system_user.password,
                        cmd=cmd)
                historys = history.objects.create(ip=i.network_ip, root=i.system_user, port=i.port, cmd=cmd, user=user)
                if s == None  or  s['data'] == '':
                    s={}
                    s['ip']=i.network_ip
                    s['data']="返回值为空,可能是权限不够。"
                ret['data'].append(s)
            except Exception as e:
                ret['data'].append({"ip": i.network_ip, "data": "账号密码不对,{}".format(e)})
        return HttpResponse(json.dumps(ret))


@login_required(login_url="/login.html")
def tools(request):
    obj = toolsscript.objects.all()
    return render(request, "tasks/tools.html",
                  {"tools": obj, "tasks_active": "active", "tools_active": "active"})


@login_required(login_url="/login.html")
def tools_add(request):
    if request.method == 'POST':
        form = ToolForm(request.POST)
        if form.is_valid():
            tools_save = form.save()
            form = ToolForm()
            return render(request, 'tasks/tools-add.html',
                          {'form': form, "tasks_active": "active", "tools_active": "active",
                           "msg": "添加成功"})
    else:
        form = ToolForm()
    return render(request, 'tasks/tools-add.html',
                  {'form': form, "tasks_active": "active", "tools_active": "active", })


@login_required(login_url="/login.html")
def tools_update(request, nid):
    tool_id = get_object_or_404(toolsscript, id=nid)

    if request.method == 'POST':
        form = ToolForm(request.POST, instance=tool_id)
        if form.is_valid():
            asset_save = form.save()
            return redirect('tools.html')

    form = ToolForm(instance=tool_id)
    return render(request, 'tasks/tools-update.html',
                  {'form': form, 'nid': nid, "tasks_active": "active", "tools_active": "active", })


@login_required(login_url="/login.html")
def tools_delete(request):
    ret = {'status': True, 'error': None, }
    if request.method == "POST":
        try:
            id_1 = request.POST.get("nid", None)
            toolsscript.objects.get(id=id_1).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,{}'.format(e)
        return HttpResponse(json.dumps(ret))


@login_required(login_url="/login.html")
def tools_bulk_delte(request):
    ret = {'status': True, 'error': None, }
    if request.method == "POST":
        try:
            ids = request.POST.getlist('id', None)
            idstring = ','.join(ids)
            toolsscript.objects.extra(where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,{}'.format(e)
        return HttpResponse(json.dumps(ret))


@login_required(login_url="/login.html")
def tools_script_post(request):
    ret = {'data': None}

    if request.method == 'POST':
        try:
            host_ids = request.POST.getlist('id', None)
            sh_id = request.POST.get('shid', None)

            user = request.user

            if not host_ids:
                error1 = "请选择主机"
                ret = {"error": error1, "status": False}
                return HttpResponse(json.dumps(ret))

            user = User.objects.get(username=request.user)
            checker = ObjectPermissionChecker(user)
            ids1 = []
            for i in host_ids:
                assets = asset.objects.get(id=i)
                if checker.has_perm('delete_asset', assets, ) == True:
                    ids1.append(i)
            idstring = ','.join(ids1)

            host = asset.objects.extra(where=['id IN (' + idstring + ')'])
            sh = toolsscript.objects.filter(id=sh_id)

            for s in sh:
                if s.tool_run_type == 0:
                    with  open('tasks/script/test.sh', 'w+') as f:
                        f.write(s.tool_script)
                        a = 'tasks/script/{}.sh'.format(s.id)
                    os.system("sed 's/\r//'  tasks/script/test.sh >  {}".format(a))

                elif s.tool_run_type == 1:
                    with  open('tasks/script/test.py', 'w+') as f:
                        f.write(s.tool_script)
                        p = 'tasks/script/{}.py'.format(s.id)
                    os.system("sed 's/\r//'  tasks/script/test.py >  {}".format(p))
                elif s.tool_run_type == 2:
                    with  open('tasks/script/test.yml', 'w+') as f:
                        f.write(s.tool_script)
                        y = 'tasks/script/{}.yml'.format(s.id)
                    os.system("sed 's/\r//'  tasks/script/test.yml >  {}".format(y))
                else:
                    ret['status'] = False
                    ret['error'] = '脚本类型错误,只能是shell、yml、python'
                    return HttpResponse(json.dumps(ret))

                data1 = []
                for h in host:
                    try:
                        data2 = {}
                        assets = [
                            {
                                "hostname": h.hostname,
                                "ip": h.network_ip,
                                "port": h.port,
                                "username": h.system_user.username,
                                "password": h.system_user.password,
                            },
                        ]

                        history.objects.create(ip=h.network_ip, root=h.system_user.username, port=h.port, cmd=s.name,
                                               user=user)
                        if s.tool_run_type == 0:
                            task_tuple = (('script', a),)
                            hoc = AdHocRunner(hosts=assets)
                            hoc.results_callback = CommandResultCallback()
                            r = hoc.run(task_tuple)
                            data2['ip'] = h.network_ip
                            data2['data'] = r['contacted'][h.hostname]['stdout']
                            data1.append(data2)


                        elif s.tool_run_type == 1:
                            task_tuple = (('script', p),)
                            hoc = AdHocRunner(hosts=assets)
                            hoc.results_callback = CommandResultCallback()
                            r = hoc.run(task_tuple)
                            data2['ip'] = h.network_ip
                            data2['data'] = r['contacted'][h.hostname]['stdout']
                            data1.append(data2)
                        elif s.tool_run_type == 2:
                            play = PlayBookRunner(assets, playbook_path=y)
                            b = play.run()
                            data2['ip'] = h.network_ip
                            data2['data'] = b['plays'][0]['tasks'][1]['hosts'][h.hostname]['stdout'] + \
                                            b['plays'][0]['tasks'][1]['hosts'][h.hostname]['stderr']
                            data1.append(data2)
                        else:
                            data2['ip'] = "脚本类型错误"
                            data2['data'] = "脚本类型错误"
                    except  Exception as  e:
                        data2['ip'] = h.network_ip
                        data2['data'] = "账号密码不对,或没有权限,请修改{}".format(e)
                        data1.append(data2)

                ret['data'] = data1

templates/tasks/cmd.html
{% extends "base.html" %}


{% block  title %}命令行{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>命令行</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>任务</a>
                </li>
                <li class="active">
                    <strong>命令行</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-5">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>命令行</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <form class="form-horizontal  cmd_from">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>外网IP</th>
                                        <th>管理IP</th>
                                        <th>产品线</th>

                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   asset_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center"><a
                                                     href="{% url  "asset:asset_detail"   pk=row.id %}">{{ row.network_ip }}</a>
                                            </td>
                                            <td class="center">{{ row.manage_ip }}</td>
                                            <td class="center">{{ row.product_line }} </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>


                                <div class="ibox-content">
                                    <div class="form-group"><label class="col-sm-2 control-label">命令</label>

                                        <div class="col-lg-8 col-sm-9"><input type="text" class="form-control" placeholder="命令" name="cmd" required=""><span class="help-block m-b-none"></span>
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-2">

                                            <a id="cmd" class="btn btn-primary" type="submit">提交</a>
                                            <button class="btn btn-white" type="button" onclick='clearBody()'>取消
                                            </button>
                                        </div>
                                    </div>

                                </div>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-7">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>输出结果
                        </h5>
                        <div class="ibox-tools">
                            <a class="collapse-links">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">配置选项 1</a>
                                </li>
                                <li><a href="#">配置选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content  pres"   >

                          <pre> <span id="err"></span></pre>

                    </div>
                </div>
            </div>
        </div>
    </div>



{% block footer-js %}

<script>


    $(function () {


        $('#cmd').click(function () {
            $.ajax({
                url: "/tasks/cmd.html",
                type: 'POST',
                data: $('.cmd_from').serialize(),
                success: function (data) {
                    var obj = JSON.parse(data);
                    cons = "";
                    if (obj.data) {
                         $.each(obj, function (data, values) {
                            $.each(values, function (index, value) {
                                cons += "<pre>"+"主机:" + value.ip + "\n" + "结果: \n " + value.data + "</pre>"

                            });
                            $(".pres").html(cons); //把内容入到这个div中即完成
                        });
                    } else {
                        $('#err').text(obj.error);
                    }

                }

            })
        });





    });

    function clearBody() {
        location.reload()
    }

</script>


{% endblock %}

{% endblock %}

templates/tasks/tools.html
{% extends "base.html" %}


{% block  title %}工具{% endblock %}

{% block page-content %}



    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>工具</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>工具</a>
                </li>
                <li class="active">
                    <strong>工具</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>工具</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                          <div class="table-responsive">

                            <a href="{% url    'tasks:tools_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <a class="btn btn-danger" data-toggle="modal"
                               data-target="#myModal2">批量删除
                            </a>





                            <form id="del_form_tools_bulk" class="form-horizontal  ">

                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>名称</th>
                                        <th>脚本类型</th>
                                        <th>工具说明</th>
                                        <th>更新时间</th>
                                        <th>动作{{ error_performance }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   tools %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input  type="checkbox"   value="{{ row.id }}"   name="id"></td>
                                            <td class="center">{{ row.name }}</td>
                                            <td class="center">{% ifequal  row.tool_run_type  0 %} shell{% endifequal  %} {% ifequal  row.tool_run_type  1 %} python {% endifequal  %}  {% ifequal row.tool_run_type  2 %}  yml {%  endifequal%}  </td>
                                            <td class="center">{{ row.comment }}</td>
                                            <td class="center">{{ row.utime }}</td>

                                            <td>
                                                <a class="btn btn-primary  btn-xs "
                                                   href="{% url  "tasks:tools_script_get"   row.id   %}">执行</a>

                                                <a class="btn btn-primary  btn-xs "
                                                   href="{% url  "tasks:tools_update"   row.id   %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  tools_del_id"     data-toggle="modal"
                                                        data-target="#myModal1">删除
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>


                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal inmodal" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">删除</h4>
                    <span id="error" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="tools_del_form">
                    <div class="modal-body">

                        <div class="form-group"><input type="text" name="nid" style="display: none;" /></div>
                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm tools_del">删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="modal inmodal" id="myModal2" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">批量删除</h4>
                    <span id="error_all" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="del_form">
                    <div class="modal-body">

                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm  asset_all_del"> 批量删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    {% block footer-js %}


        <script>
            $(function () {

                $('.tools_del_id').click(function () {
                    var   id = $(this).parent().parent().attr('id');
                    $('#tools_del_form').find('input[name="nid"]').val(id);


                });
                $('.tools_del').click(function () {
                    $.ajax({
                        url: "/tasks/tools-del.html",
                        type: 'POST',
                        data: $('#tools_del_form').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.reload()
                            } else {
                                $('#error').text(obj.error);
                            }
                        }
                    })
                });

                $('.asset_all_del').click(function () {
                    $.ajax({
                        url: "/tasks/tools-bulk-del.html",
                        type: 'POST',
                        data: $('#del_form_tools_bulk').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.reload()
                            } else {
                                $('#error_all').text(obj.error);
                            }
                        }

                    })
                });


            });



</script>


{% endblock %}

{% endblock %}